public class ThrowException01 {
    public static void main(String[] args) {
        try {
            // Generamos una excepci贸n con un mensaje
            throw new Exception("\nEsto es una excepci贸n");
        } catch (Exception e) {
            // Capturamos la excepci贸n y mostramos el mensaje
            System.out.println("\nSe ha producido una excepci贸n: " + e.getMessage());
        } finally {
            // Este bloque siempre se ejecuta
            System.out.println("Bloque finally ejecutado\n");
        }
    }
}
